export const REGISTER_USER = 'REGISTER';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const LOGIN_USER = 'LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const AUTH_LOADING = 'AUTH_LOADING';
export const PROCESSING_REQUEST = 'PROCESSING_REQUEST';
export const CLEAR_AUTH_ERRORS = 'CLEAR_AUTH_ERRORS';
